/*
 * Copyright (c) 2021 AGT Group (R&D) GmbH. All rights reserved.
 * Redistribution and use in source and binary form without the express
 * permission of the above copyright holder is not permitted.
 */

//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// CoachAI Core Version: 13.2.3
// Generated On: 2022-06-13T13:29:09Z
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CoachAiEngine;
using System.Linq;
using UnityEngine;
using UnityEngine.Events;

namespace CoachAiEngine.Analytics {

    [System.CodeDom.Compiler.GeneratedCode(tool: "Coach-Ai engine", version: "13.2.3")]
    [CreateAssetMenu(fileName = nameof(BallSpeedEstimator), menuName = "Coach-AI Engine/Components/BallSports/BallSpeedEstimator")]
    public class BallSpeedEstimator : CoachComponent {

        public override string ComponentId => "com.coachai.engine.analytics.ball.components.BallSpeedEstimator";
        private static readonly string[] eventIds =  {
            "com.coachai.engine.analytics.ball.pipeline.PartialParabolaBallSpeedEvent"
        };

        private static readonly float BallSpeedImpactDeltaVThreshold = 2.0f;
        private static readonly int BallKickTimeout = 2000;
        private static readonly int BallSpeedEstimatorHistorySize = 10;

        [Tooltip("Velocity change threshold (m/s). Minimum speed change for detecting a kick. Larger values require stronger kicks and ignore slight kicks. Lower values allow slighter kicks, but might also introduce false positives.")]
        public float ballSpeedImpactDeltaVThreshold = BallSpeedImpactDeltaVThreshold;
        [Tooltip("Timeout after a kick is detected and a new kick can be recognised.")]
        public int ballKickTimeout = BallKickTimeout;
        [Tooltip("last N [ParabolaPartial] used to calculate median speeds")]
        public int ballSpeedEstimatorHistorySize = BallSpeedEstimatorHistorySize;

        public override Dictionary<string, object> Parameters {
            get {
                var parameters = new Dictionary<string, object>();

                AddUnlessDefault("BallSpeedImpactDeltaVThreshold",
                    ballSpeedImpactDeltaVThreshold, BallSpeedImpactDeltaVThreshold, parameters
                );
                AddUnlessDefault("BallKickTimeout",
                    ballKickTimeout, BallKickTimeout, parameters
                );
                AddUnlessDefault("com.coachai.engine.analytics.ball.components.BallSpeedEstimatorHistorySize",
                    ballSpeedEstimatorHistorySize, BallSpeedEstimatorHistorySize, parameters
                );
                return parameters;
            }
        }

        private void AddUnlessDefault<T>(string key, T value, T @default, Dictionary<string, object> parameters) {
            if (value.Equals(@default)) return;
            parameters.Add(key, value);
        }

        public override List<string> PublishedEventIds => eventIds.ToList();

    }
}