/*
 * Copyright (c) 2021 AGT Group (R&D) GmbH. All rights reserved.
 * Redistribution and use in source and binary form without the express
 * permission of the above copyright holder is not permitted.
 */

//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// CoachAI Core Version: 13.2.3
// Generated On: 2022-06-13T13:29:09Z
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CoachAiEngine;
using System.Linq;
using UnityEngine;
using UnityEngine.Events;

namespace CoachAiEngine.Analytics {

    [System.CodeDom.Compiler.GeneratedCode(tool: "Coach-Ai engine", version: "13.2.3")]
    [CreateAssetMenu(fileName = nameof(BallActionAnalytics), menuName = "Coach-AI Engine/Components/BallSports/BallActionAnalytics")]
    public class BallActionAnalytics : CoachComponent {

        public override string ComponentId => "com.coachai.engine.analytics.action.components.BallActionAnalytics";
        private static readonly string[] eventIds =  {
            "com.coachai.engine.analytics.action.NetworkFeatureEvent",
            "com.coachai.engine.analytics.action.BallAction"
        };

        private static readonly BallActionModelParameterType BallActionModelParameter = BallActionModelParameterType.ActionBallJuggling10c17luBall1fsSoccerV4;
        private static readonly bool EnableStabilityFiltering = true;

        [Tooltip("Choose a ball action model. Please read model documentation to be aware of the use cases and limitations.")]
        public BallActionModelParameterType ballActionModelParameter = BallActionModelParameter;
        [Tooltip("If enabled, the actions pipeline will take additional information on pose and ball in order to detect false detections in which case no actions are produced")]
        public bool enableStabilityFiltering = EnableStabilityFiltering;

        public override Dictionary<string, object> Parameters {
            get {
                var parameters = new Dictionary<string, object>();

                AddUnlessDefault("ballaction.com.coachai.engine.analytics.action.components.BallActionModelParameter",
                    BallActionModelParameterTypeLookup[ballActionModelParameter], BallActionModelParameterTypeLookup[BallActionModelParameter], parameters
                );
                AddUnlessDefault("ballaction.com.coachai.engine.analytics.action.components.EnableStabilityFiltering",
                    enableStabilityFiltering, EnableStabilityFiltering, parameters
                );
                return parameters;
            }
        }

        private void AddUnlessDefault<T>(string key, T value, T @default, Dictionary<string, object> parameters) {
            if (value.Equals(@default)) return;
            parameters.Add(key, value);
        }

        public override List<string> PublishedEventIds => eventIds.ToList();

        public enum BallActionModelParameterType {
            ActionBallJuggling10c17luBall1fsSoccerV4,
            ActionBallPendulum3c17luBall1fsSoccerV3,
            ActionBallTapping7c17luBall1fsSoccerV3,
            ActionBallDribbling4c17luBall1fsBasketballV3,
            ActionBallKick2c17luBall1fsSoccerV6
        }

        public Dictionary<BallActionModelParameterType, string> BallActionModelParameterTypeLookup = new Dictionary<BallActionModelParameterType, string> {
            { BallActionModelParameterType.ActionBallJuggling10c17luBall1fsSoccerV4, "action.ball-juggling-10c.17lu-ball-1fs.soccer_4 v4" },
            { BallActionModelParameterType.ActionBallPendulum3c17luBall1fsSoccerV3, "action.ball-pendulum-3c.17lu-ball-1fs.soccer_3 v3" },
            { BallActionModelParameterType.ActionBallTapping7c17luBall1fsSoccerV3, "action.ball-tapping-7c.17lu-ball-1fs.soccer_1 v1" },
            { BallActionModelParameterType.ActionBallDribbling4c17luBall1fsBasketballV3, "action.ball-dribbling-4c.17lu-ball-1fs.basketball_3 v3" },
            { BallActionModelParameterType.ActionBallKick2c17luBall1fsSoccerV6, "action.ball-kick-2c.17lu-ball-1fs.soccer_6 v6" }
        };

    }
}