/*
 * Copyright (c) 2021 AGT Group (R&D) GmbH. All rights reserved.
 * Redistribution and use in source and binary form without the express
 * permission of the above copyright holder is not permitted.
 */

//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// CoachAI Core Version: 13.2.3
// Generated On: 2022-06-13T13:29:09Z
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CoachAiEngine;
using System.Linq;
using UnityEngine;
using UnityEngine.Events;

namespace CoachAiEngine.Analytics {

    [System.CodeDom.Compiler.GeneratedCode(tool: "Coach-Ai engine", version: "13.2.3")]
    [CreateAssetMenu(fileName = nameof(CameraPlacementAnalytics), menuName = "Coach-AI Engine/Components/Core/CameraPlacementAnalytics")]
    public class CameraPlacementAnalytics : CoachComponent {

        public override string ComponentId => "com.coachai.engine.cameraplacement.CameraPlacementAnalytics";
        private static readonly string[] eventIds =  {
            "com.coachai.engine.cameraplacement.CameraPlacementEvent"
        };

        private static readonly bool CameraPlacementFixedCameraHeight = false;
        private static readonly float CameraPlacementFixedCameraHeightValue = 1.0f;
        private static readonly bool CameraPlacementFixedRotation = false;
        private static readonly bool CameraPlacementFixedRotationPortraitValue = false;

        [Tooltip("Enable usage of fixed value for the height of the camera, to avoid recalculations during movement.")]
        public bool cameraPlacementFixedCameraHeight = CameraPlacementFixedCameraHeight;
        [Tooltip("Assume camera is always at this height [m].")]
        public float cameraPlacementFixedCameraHeightValue = CameraPlacementFixedCameraHeightValue;
        [Tooltip("Enable usage of fixed value for the rotation of the camera, to avoid accidental recalculations")]
        public bool cameraPlacementFixedRotation = CameraPlacementFixedRotation;
        [Tooltip("Calculate the device rotation as being always Portrait or Landscape")]
        public bool cameraPlacementFixedRotationPortraitValue = CameraPlacementFixedRotationPortraitValue;

        public override Dictionary<string, object> Parameters {
            get {
                var parameters = new Dictionary<string, object>();

                AddUnlessDefault("com.coachai.engine.cameraplacement.CameraPlacementFixedCameraHeight",
                    cameraPlacementFixedCameraHeight, CameraPlacementFixedCameraHeight, parameters
                );
                AddUnlessDefault("com.coachai.engine.cameraplacement.CameraPlacementFixedCameraHeightValue",
                    cameraPlacementFixedCameraHeightValue, CameraPlacementFixedCameraHeightValue, parameters
                );
                AddUnlessDefault("com.coachai.engine.cameraplacement.CameraPlacementFixedRotation",
                    cameraPlacementFixedRotation, CameraPlacementFixedRotation, parameters
                );
                AddUnlessDefault("com.coachai.engine.cameraplacement.CameraPlacementFixedRotationPortraitValue",
                    cameraPlacementFixedRotationPortraitValue, CameraPlacementFixedRotationPortraitValue, parameters
                );
                return parameters;
            }
        }

        private void AddUnlessDefault<T>(string key, T value, T @default, Dictionary<string, object> parameters) {
            if (value.Equals(@default)) return;
            parameters.Add(key, value);
        }

        public override List<string> PublishedEventIds => eventIds.ToList();

    }
}