/*
 * Copyright (c) 2021 AGT Group (R&D) GmbH. All rights reserved.
 * Redistribution and use in source and binary form without the express
 * permission of the above copyright holder is not permitted.
 */

//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// CoachAI Core Version: 13.2.3
// Generated On: 2022-06-13T13:29:09Z
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CoachAiEngine;
using System.Linq;
using UnityEngine;
using UnityEngine.Events;

namespace CoachAiEngine.Analytics {

    [System.CodeDom.Compiler.GeneratedCode(tool: "Coach-Ai engine", version: "13.2.3")]
    [CreateAssetMenu(fileName = nameof(HandPoseAnalytics), menuName = "Coach-AI Engine/Components/HumanBody/HandPoseAnalytics (Experimental)")]
    public class HandPoseAnalytics : CoachComponent {

        public override string ComponentId => "com.coachai.engine.analytics.pose.components.HandPoseAnalytics";
        private static readonly string[] eventIds =  {
            "com.coachai.engine.analytics.pose.HandResult",
            "com.coachai.engine.analytics.pose.FullBodyPoseResult"
        };

        private static readonly HandPoseModelType HandPoseModel = HandPoseModelType.HandPoseSingle21h2d3d1fGeneralLightV1;
        private static readonly int TargetFPS = 30;
        private static readonly int MaximumInboundQueueSize = 2;

        [Tooltip("Choose a hand model. Please read model documentation to be aware of the use cases and limitations.")]
        public HandPoseModelType handPoseModel = HandPoseModel;
        [Tooltip("Set maximum allowed processed frames per second")]
        public int targetFPS = TargetFPS;
        [Tooltip("Set maximum allowed inbound events to put into processing queue")]
        public int maximumInboundQueueSize = MaximumInboundQueueSize;

        public override Dictionary<string, object> Parameters {
            get {
                var parameters = new Dictionary<string, object>();

                AddUnlessDefault("com.coachai.engine.analytics.pose.components.HandPoseModel",
                    HandPoseModelTypeLookup[handPoseModel], HandPoseModelTypeLookup[HandPoseModel], parameters
                );
                AddUnlessDefault("com.coachai.engine.analytics.pose.parameters.TargetFPS",
                    targetFPS, TargetFPS, parameters
                );
                AddUnlessDefault("com.coachai.engine.analytics.pose.parameters.MaximumInboundQueueSize",
                    maximumInboundQueueSize, MaximumInboundQueueSize, parameters
                );
                return parameters;
            }
        }

        private void AddUnlessDefault<T>(string key, T value, T @default, Dictionary<string, object> parameters) {
            if (value.Equals(@default)) return;
            parameters.Add(key, value);
        }

        public override List<string> PublishedEventIds => eventIds.ToList();

        public enum HandPoseModelType {
            HandPoseModelBatch1SmallV1,
            HandPoseModelBatch1MediumV1,
            HandPoseModelBatch1LargeV1,
            HandPoseModelBatch2SmallV6,
            HandPoseModelBatch2MediumV6,
            HandPoseModelBatch2LargeV6,
            HandPoseSingle21h2d3d1fGeneralLightV1,
            HandPoseSingle21h2d3d1fGeneralMediumV1
        }

        public Dictionary<HandPoseModelType, string> HandPoseModelTypeLookup = new Dictionary<HandPoseModelType, string> {
            { HandPoseModelType.HandPoseModelBatch1SmallV1, "hand.coach-analytics-small-b1 v1 (Experimental)" },
            { HandPoseModelType.HandPoseModelBatch1MediumV1, "hand.coach-analytics-medium-b1 v1 (Experimental)" },
            { HandPoseModelType.HandPoseModelBatch1LargeV1, "hand.coach-analytics-large-b1 v1 (Experimental)" },
            { HandPoseModelType.HandPoseModelBatch2SmallV6, "hand.coach-analytics-small v6 (Experimental)" },
            { HandPoseModelType.HandPoseModelBatch2MediumV6, "hand.coach-analytics-medium v6 (Experimental)" },
            { HandPoseModelType.HandPoseModelBatch2LargeV6, "hand.coach-analytics-large v6 (Experimental)" },
            { HandPoseModelType.HandPoseSingle21h2d3d1fGeneralLightV1, "hand-pose.single-21h-2d-3d.1f.general.light v1" },
            { HandPoseModelType.HandPoseSingle21h2d3d1fGeneralMediumV1, "hand-pose.single-21h-2d-3d.1f.general.medium v1" }
        };

    }
}