/*
 * Copyright (c) 2021 AGT Group (R&D) GmbH. All rights reserved.
 * Redistribution and use in source and binary form without the express
 * permission of the above copyright holder is not permitted.
 */

//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// CoachAI Core Version: 13.2.3
// Generated On: 2022-06-13T13:29:09Z
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CoachAiEngine;
using System.Linq;
using UnityEngine;
using UnityEngine.Events;

namespace CoachAiEngine.Analytics {

    [System.CodeDom.Compiler.GeneratedCode(tool: "Coach-Ai engine", version: "13.2.3")]
    [CreateAssetMenu(fileName = nameof(PoseActionDetectorAnalytics), menuName = "Coach-AI Engine/Components/MotionRecognition/PoseActionDetectorAnalytics")]
    public class PoseActionDetectorAnalytics : CoachComponent {

        public override string ComponentId => "com.coachai.engine.analytics.pose.components.PoseActionDetectorAnalytics";
        private static readonly string[] eventIds =  {
            "com.coachai.engine.analytics.pose.semantic.actions.ActionDetection",
            "com.coachai.engine.analytics.pose.semantic.actions.EnrichedActionDetection"
        };

        private static readonly string ActionDetectorConfig = "parameter.defaultValue.toString()";
        private static readonly ActionDetectorConfigInputTypeType ActionDetectorConfigInputType = ActionDetectorConfigInputTypeType.Json;

        [Tooltip("Specifies the json string or path that will be used for configuration of the component")]
        public string actionDetectorConfig = ActionDetectorConfig;
        [Tooltip("Specifies if the json has been passed as string or path")]
        public ActionDetectorConfigInputTypeType actionDetectorConfigInputType = ActionDetectorConfigInputType;

        public override Dictionary<string, object> Parameters {
            get {
                var parameters = new Dictionary<string, object>();

                AddUnlessDefault("com.coachai.engine.analytics.pose.components.ActionDetectorConfig",
                    actionDetectorConfig, ActionDetectorConfig, parameters
                );
                AddUnlessDefault("com.coachai.engine.analytics.pose.components.ActionDetectorConfigInputType",
                    ActionDetectorConfigInputTypeTypeLookup[actionDetectorConfigInputType], ActionDetectorConfigInputTypeTypeLookup[ActionDetectorConfigInputType], parameters
                );
                return parameters;
            }
        }

        private void AddUnlessDefault<T>(string key, T value, T @default, Dictionary<string, object> parameters) {
            if (value.Equals(@default)) return;
            parameters.Add(key, value);
        }

        public override List<string> PublishedEventIds => eventIds.ToList();

        public enum ActionDetectorConfigInputTypeType {
            Json,
            InlineJson
        }

        public Dictionary<ActionDetectorConfigInputTypeType, string> ActionDetectorConfigInputTypeTypeLookup = new Dictionary<ActionDetectorConfigInputTypeType, string> {
            { ActionDetectorConfigInputTypeType.Json, "Json" },
            { ActionDetectorConfigInputTypeType.InlineJson, "InlineJson" }
        };

    }
}